### PR TITLE
Release `v0.1.1`

### PR DESCRIPTION
**Pull request by robbot006**
This is a draft of changelog for the `v0.1.1` release.
Here you can find all related translations changes: [v0.1.0...master](https://github.com/neerugupta/flarum-lang-arabic/compare/v0.1.0...master).

> ### ⚠️ Do not merge this pull request manually ⚠️
> 
> You should [approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request) this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release.

<details>
<summary>Show release notes preview</summary>

## v0.1.1

**General changes**:

* Updated Flarum core translations.

**Added support for new extensions**:

* [`acpl/flarum-lscache`](https://github.com/android-com-pl/flarum-lscache)
* [`acpl/mobile-tab`](https://github.com/android-com-pl/mobile-tab)
* [`acpl/my-tags`](https://github.com/android-com-pl/my-tags)
* [`afrux/asirem`](https://github.com/afrux/asirem)
* [`afrux/forum-stats-widget`](https://github.com/afrux/forum-stats-widget)
* [`afrux/forum-widgets-core`](https://github.com/afrux/forum-widgets-core)
* [`afrux/news-widget`](https://github.com/afrux/news-widget)
* [`afrux/online-users-widget`](https://github.com/afrux/online-users-widget)
* [`afrux/top-posters-widget`](https://github.com/afrux/top-posters-widget)
* [`antoinefr/flarum-ext-money`](https://github.com/AntoineFr/flarum-ext-money)
* [`antoinefr/flarum-ext-online`](https://github.com/AntoineFr/flarum-ext-online)
* [`askvortsov/flarum-article-series`](https://github.com/askvortsov1/flarum-article-series)
* [`askvortsov/flarum-auto-moderator`](https://github.com/askvortsov1/flarum-auto-moderator)
* [`askvortsov/flarum-categories`](https://github.com/askvortsov1/flarum-categories)
* [`askvortsov/flarum-checklist`](https://github.com/askvortsov1/flarum-checklist)
* [`askvortsov/flarum-discussion-templates`](https://github.com/askvortsov1/flarum-discussion-templates)
* [`askvortsov/flarum-help-tags`](https://github.com/askvortsov1/flarum-help-tags)
* [`askvortsov/flarum-markdown-tables`](https://github.com/askvortsov1/flarum-markdown-tables)
* [`askvortsov/flarum-moderator-warnings`](https://github.com/askvortsov1/flarum-moderator-warnings)
* [`askvortsov/flarum-pwa`](https://github.com/askvortsov1/flarum-pwa)
* [`askvortsov/flarum-rich-text`](https://github.com/askvortsov1/flarum-rich-text)
* [`blomstra/flag-duplicates`](https://github.com/blomstra/flarum-ext-flag-duplicate)
* [`blomstra/mark-unread`](https://github.com/blomstra/flarum-ext-mark-unread)
* [`blomstra/notification-deleter`](https://github.com/blomstra/flarum-ext-notification-deleter)
* [`blomstra/payments`](https://extiverse.com/extension/blomstra/payments)
* [`blomstra/readme`](https://extiverse.com/extension/blomstra/readme)
* [`flarum/nicknames`](https://github.com/flarum/nicknames)

All changes: [v0.1.0...v0.1.1](https://github.com/neerugupta/flarum-lang-arabic/compare/v0.1.0...v0.1.1).

</details>

### CODE REVIEW

**Comment by rob006** [comment]
Just as a note, this is an automated PR generated by bot. The idea is to simplify release process for language pack maintainers - all you need is to approve this pull request and bot will handle the rest. You can read more the process at forum: https://discuss.flarum.org/d/20807-simplify-translation-process-with-weblate/76 . If you don't want to use this feature, let me know.

Also, please take a look at https://github.com/rob006-software/flarum-translations/issues/920. Because this is private repository I can't setup webhooks correctly, so bot may be quite slow to respond. Migrating repository under `flraum-lang` org would help with that.

**Review by neerugupta — APPROVED** [review]
LGTM

**Comment by robbot006** [comment]
Success! Now you can announce new release on [forum](https://discuss.flarum.org/t/languages):

~~~markdown
## Version [`v0.1.1`](https://github.com/neerugupta/flarum-lang-arabic/releases/tag/v0.1.1)

**General changes**:

* Updated Flarum core translations.


**Added support for new extensions**:

* [`acpl/flarum-lscache`](https://github.com/android-com-pl/flarum-lscache)
* [`acpl/mobile-tab`](https://github.com/android-com-pl/mobile-tab)
* [`acpl/my-tags`](https://github.com/android-com-pl/my-tags)
* [`afrux/asirem`](https://github.com/afrux/asirem)
* [`afrux/forum-stats-widget`](https://github.com/afrux/forum-stats-widget)
* [`afrux/forum-widgets-core`](https://github.com/afrux/forum-widgets-core)
* [`afrux/news-widget`](https://github.com/afrux/news-widget)
* [`afrux/online-users-widget`](https://github.com/afrux/online-users-widget)
* [`afrux/top-posters-widget`](https://github.com/afrux/top-posters-widget)
* [`antoinefr/flarum-ext-money`](https://github.com/AntoineFr/flarum-ext-money)
* [`antoinefr/flarum-ext-online`](https://github.com/AntoineFr/flarum-ext-online)
* [`askvortsov/flarum-article-series`](https://github.com/askvortsov1/flarum-article-series)
* [`askvortsov/flarum-auto-moderator`](https://github.com/askvortsov1/flarum-auto-moderator)
* [`askvortsov/flarum-categories`](https://github.com/askvortsov1/flarum-categories)
* [`askvortsov/flarum-checklist`](https://github.com/askvortsov1/flarum-checklist)
* [`askvortsov/flarum-discussion-templates`](https://github.com/askvortsov1/flarum-discussion-templates)
* [`askvortsov/flarum-help-tags`](https://github.com/askvortsov1/flarum-help-tags)
* [`askvortsov/flarum-markdown-tables`](https://github.com/askvortsov1/flarum-markdown-tables)
* [`askvortsov/flarum-moderator-warnings`](https://github.com/askvortsov1/flarum-moderator-warnings)
* [`askvortsov/flarum-pwa`](https://github.com/askvortsov1/flarum-pwa)
* [`askvortsov/flarum-rich-text`](https://github.com/askvortsov1/flarum-rich-text)
* [`blomstra/flag-duplicates`](https://github.com/blomstra/flarum-ext-flag-duplicate)
* [`blomstra/mark-unread`](https://github.com/blomstra/flarum-ext-mark-unread)
* [`blomstra/notification-deleter`](https://github.com/blomstra/flarum-ext-notification-deleter)
* [`blomstra/payments`](https://extiverse.com/extension/blomstra/payments)
* [`blomstra/readme`](https://extiverse.com/extension/blomstra/readme)
* [`flarum/nicknames`](https://github.com/flarum/nicknames)


All changes: [v0.1.0...v0.1.1](https://github.com/neerugupta/flarum-lang-arabic/compare/v0.1.0...v0.1.1).

In order to update run these commands:

```console
composer update neerugupta/flarum-lang-arabic
php flarum cache:clear
```

~~~

**Comment by rob006** [comment]
@neerugupta What about https://github.com/rob006-software/flarum-translations/issues/920 and moving to `flarum-lang`?

**Pull request merged**
